capbot_joint_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 100

capbot_velocity_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'L_joint'
    right_wheel : 'R_joint'
    publish_rate: 100
    
    enable_odom_tf: false
    
    pose_covariance_diagonal : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # Wheel separation and radius
    wheel_separation : 0.4
    wheel_radius : 0.115
    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0

    # Base frame_id
    base_frame_id: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        #max_velocity           : 0.4  # m/s
        #min_velocity           : -0.4 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.4  # m/s^2
        min_acceleration       : -0.4 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        #max_velocity           : 0.5  # rad/s
        has_acceleration_limits: true
        #max_acceleration       : 0.5  # rad/s^2
